Traceback (most recent call last):
  File "data_preprocessing_v1.py", line 144, in <module>
    balances_test = pd.read_csv(f'{data_path}balances_test.csv')
  File "/home/userbda/Proyectos/analisis_calidad/analisis/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/userbda/Proyectos/analisis_calidad/analisis/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/userbda/Proyectos/analisis_calidad/analisis/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/userbda/Proyectos/analisis_calidad/analisis/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/userbda/Proyectos/analisis_calidad/analisis/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '../../datasetsbalances_test.csv'
